version: "3.6"

services:
  puller:
    build: .
    restart: always
    volumes:
     - /etc/:/local_etc/
     - /var/run/docker.sock:/var/run/docker.sock
     - ~/.docker/config.json:/root/.docker/config.json  # Mount Docker config
    ports:
      - '4999:4999'
    environment:
      SERVER_PORT: 4999


